---
- name: Add a new user to RHEL 8 host
  hosts: "{{ _hosts  | default(omit) }}"
  become: true
  # vars:
  #   username: "Mike Linux"
  #   group1: wheel

  tasks:
    - name: Add user
      ansible.builtin.user:
        name: "{{ username }}"
        comment: "Mike Tyson"
        # shell: /bin/bash
        # create_home: true
        home: /home/"{{ username }}"
        groups: wheel
        # Optionally set a password (encrypted)
        password: "$6$66oTgAFogC56Y8VU$NNck2nIO41HHMqxndiESm1aOcXAY8VRIF3A3cGvOcZO60kFfiXrklnThDGCAhEy0mfkEr2BP7U2hY5oQKcF3V."
        state: present

    - name: Display contents of etc/passwd
      ansible.builtin.command:
        cmd: cat /etc/passwd
      register: passwd_contents

    - name: Print /etc/passwd contents
      ansible.builtin.debug:
        msg: "{{ passwd_contents.stdout_lines }}"
